name: HitEndCrystal
version: '${version}'
main: me.mapacheee.hitendcrystal.HitEndCrystalPlugin
api-version: '1.21'
depend: [WorldGuard]
softdepend: [PlaceholderAPI]
authors: [Mapacheee]
description: Click counter plugin for End Crystals in lobbies

permissions:
  hitendcrystal.admin:
    description: Admin permissions for HitEndCrystal
    default: op
  hitendcrystal.use:
    description: Use the click counter
    default: true

